# This is a basic workflow to help you get started with Actions



name: ChristianHFlow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

#      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Notice here I'm building and releasing my solution.
      # This allows me to use the packages - fx from the Function or the Webapp
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - run: |
          az webapp list --query "[?state=='Running']"
      
      - name: Deploy resources
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\deploy-resources.ps1
          azPSVersion: "latest"
      
      
      
      
